package usecase;

public enum Modules {
	REMS, TELECOMM, RAD, ATTNCRTL, THERMAL, MASTCAM, NAVCAM, CHEMMIN, COMMAND, MAHLI, CHEMCAM, PADS, PWRBATT, SAM, HAZCAM, 
	ARM, APXS, MOBILITY1, DAN, FAULT, MOBILITY2;
}
